# Site settings
title: 'databhishek'
description: >
  Hi, I'm Abhishek. I like to learn new things and occasionally write about them here.

author: Abhishek Singh
email: abhi.aryan98@gmail.com
twitter_username: databhishek
github_username: databhishek

baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://databhishek.me' # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics_id: UA-71070640-2
disqus_id: databhishek

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:title

sass:
  style: compressed

exclude: [vendor]
