title: Abhishek Singh
email: abhi.aryan98@gmail.com
description: >
  I've done some questionable things in life.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://databhishek.github.io" # the base hostname & protocol for your site
postCount: 5 # the number of posts on the "index" page

github_username: databhishek
twitter_username: databhishek

# Build settings
markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md
permalink   : /:year/:title/
source: ./
destination: ./_site

gems:
  - jekyll-sitemap
  
