name: Abhishek Singh
description: Programmer
meta_description: SO IT GOES.

markdown: kramdown
highlighter: rouge
logo: true
paginate: 15
baseurl: /
disqus: databhishek
domain_name: 'http://databhishek.github.io'
google_analytics: 'UA-71070640-2'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'www.abhisheksingh.org'
author:         'Abhishek Singh'
