# Site settings
title: 'Abhishek Singh'
description: >
  hey, i'm abhishek. i'm a software engineer. nice to meet you!

author: Abhishek Singh
email: abhi.aryan98@gmail.com
twitter_username: databhishek
github_username: databhishek

baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://abhshk.me' # the base hostname & protocol for your site
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics_id: UA-71070640-2
disqus_id: databhishek

# Build settings
include: [_pages]
markdown: kramdown
permalink: /:title

sass:
  style: compressed
