name: Abhishek Singh
description: Musings of a polymath.
meta_description: "I code and watch Silicon Valley."

aboutPage: true

markdown: kramdown
highlighter: rouge

gems: [jekyll-paginate]
paginate: 20
baseurl: /
domain_name: 'http://databhishek.github.io'
google_analytics: 'UA-71070640-2'
disqus: true
disqus_shortname: 'databhishek'

# Details for the RSS feed generator
url:            'http://databhishek.github.io'
author:         'Abhishek Singh'
authorTwitter:  'databhishek'

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
