# Jekyll Defaults
title: Abhishek Singh
description: Musings of a Computer Science student
baseurl: "" # the subpath of your site, e.g. /blog

tracking_id:	UA-71070640-1

url: "http://abhisheksingh.me"
github: http://github.com/databhishek
highlighter: rouge
markdown: kramdown
permalink: /post/:title/
paginate: 4
gems: [jekyll-paginate]
paginate_path: "/page:num"
rss_path: /feed.xml
navigation:
- text: About
  url: /about/
- text: Archives
  url: /archives/
- text: RSS
  url: /feed.xml/
